apiVersion: batch/v1
kind: Job
metadata:
  name: klar
spec:
  template:
    spec:
      hostAliases:
        - ip: "18.213.137.78"
          hostnames:
            - "registry-1.docker.io"
      containers:
      - name: klar
        image: leahnp/klar-scratch
        args:
          - "strusfr/docker-ubuntu1604-slurmctld:latest"
        env:
          - name: CLAIR_ADDR
            value: "http://clairsvc.rack01.svc.cluster.local:6060"
          - name: CLAIR_OUTPUT
            value: "High"
          - name: CLAIR_THRESHOLD
            value: "10"
      restartPolicy: Never
  backoffLimit: 4