apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronyd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: chronyd
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: chronyd
    spec:
      hostAliases:
      - ip: "10.0.0.2"
        hostnames:
        - "node01"
        - "node01.home.lab"
      - ip: "10.0.0.3"
        hostnames:
        - "node02"
        - "node02.home.lab"
      - ip: "10.0.0.4"
        hostnames:
        - "node03"
        - "node03.home.lab"
      - ip: "10.0.0.5"
        hostnames:
        - "node04"
        - "node04.home.lab"
      - ip: "10.0.0.6"
        hostnames:
        - "node05"
        - "node05.home.lab"
      - ip: "10.0.0.9"
        hostnames:
        - "node09"
        - "node09.home.lab"
      containers:
      - name: chronyd
        image: alvistack/chrony:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["NET_ADMIN","SYS_TIME"]
        resources:
          limits:
            cpu: 20m
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 64Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/chrony/chrony.conf
          subPath: chrony.conf
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
            name: chrony-conf

---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: chronyd
  name: chrony-conf
  namespace: kube-system
data:
  # Configuration values can be set as key-value properties
  chrony.conf: |
    server 10.0.0.210

---
apiVersion: v1
kind: Service
metadata:
  name: chronyd
  namespace: kube-system
  labels:
    app: chronyd
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.11
  ports:
    - port: 123
      targetPort: 123
      protocol: UDP
      name: chronyd