kind: Namespace
apiVersion: v1
metadata:
  name: kube-system

---
kind: Namespace
apiVersion: v1
metadata:
  name: rack01

---
kind: Namespace
apiVersion: v1
metadata:
  name: rack02

---
kind: Namespace
apiVersion: v1
metadata:
  name: kubernetes-dashboard

---
kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager

---
kind: Namespace
apiVersion: v1
metadata:
  name: nginx-ingress