kind: Namespace
apiVersion: v1
metadata:
  name: kube-system

---
kind: Namespace
apiVersion: v1
metadata:
  name: coredns

---
kind: Namespace
apiVersion: v1
metadata:
  name: monitoring

---
kind: Namespace
apiVersion: v1
metadata:
  name: ftpsvc

---
kind: Namespace
apiVersion: v1
metadata:
  name: slurm-ns

---
kind: Namespace
apiVersion: v1
metadata:
  name: registry

---
kind: Namespace
apiVersion: v1
metadata:
  name: kubernetes-dashboard