apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    frontend: nginx
spec:
  selector:
    matchLabels:
      frontend: nginx
  replicas: 1
  template:
    metadata:
      labels:
        frontend: nginx
    spec:
      containers:
      - name: gatekeeper
        image: keycloak/keycloak-gatekeeper:7.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: service
        args:
        - --config=/etc/secrets/gatekeeper.yaml
        - --redirection-url=https://netbox.home.lab
        - --upstream-url=http://127.0.0.1:80
        - --resources=uri=/*|roles=Admin
        volumeMounts:
          - name: gatekeeper-secrets
            mountPath: /etc/secrets
      - name: nginx
        image: nginx:1.12-alpine
        #ports:
        #- containerPort: 80
        command: ["nginx"]
        args: ["-c", "/etc/netbox-nginx/nginx.conf","-g", "daemon off;"] 
        volumeMounts:
        - name: netbox-static-files
          mountPath: /opt/netbox/netbox/static
        - name: netbox-nginx-config
          mountPath: /etc/netbox-nginx 
      restartPolicy: Always
      volumes:
      - name: netbox-static-files
        persistentVolumeClaim:
          claimName: netbox-static-files
      - name: netbox-nginx-config
        configMap:
          name: nginx-conf
      - name: gatekeeper-secrets
        secret:
          secretName: gatekeeper
       
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    frontend: nginx
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    frontend: nginx

