apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: rack01
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/instance: lab-coredns
data:
  Corefile: |
    .:53 {
        # Automatically load zone files mounted in the "zones" directory
        auto {
            directory /etc/coredns/zones
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
        }
        # Enable logging to STDOUT
        log
        # Print errors to STDOUT
        errors
        prometheus :9153
        forward . /etc/resolv.conf
        # Automatically load changes to the Corefile
        reload 30s
        # Round-robin A, AAAA and PTR records
        loadbalance
        # Return HTTP 200 OK on :8080 when CoreDNS is running
        health
        # Return HTTP 200 OK on :8081 when CoreDNS and plugins are ready
        ready
    }
