---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-dyn"
spec:
  # selector:
  #   matchLabels:
  #     app: registry
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi