---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryui
  namespace: registry
spec:
  selector:
    matchLabels:
      app: registryui
  replicas: 1
  template:
    metadata:
      labels:
        app: registryui
    spec:
      containers:
      - name: registryui
        image: konradkleine/docker-registry-frontend:v2
        imagePullPolicy: IfNotPresent
        env:
          - name: ENV_DOCKER_REGISTRY_HOST
            value: "10.0.0.10"
          - name: ENV_DOCKER_REGISTRY_PORT
            value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: registryui
  namespace: registry
spec:
  selector:
    app: registryui
  ports:
    - name: tcp80
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.0.0.26