kind: ConfigMap
apiVersion: v1
metadata:
  name: coredns-zones
  namespace: coredns
data:
  db.home.lab: |
    $TTL  30M
    @ IN SOA ns1.home.lab. home.lab. (
        20200101 ; serial
        4H ; refresh
        1H ; retry
        7D ; expire
        4H); Negative Cache TTL
      IN NS ns1
    ns1       IN A 10.0.0.1.150
    node01.home.lab    IN A 10.0.0.2
    node02.home.lab    IN A 10.0.0.3
    node03.home.lab    IN A 10.0.0.4
    node04.home.lab    IN A 10.0.0.5
    node05.home.lab    IN A 10.0.0.6
    node09.home.lab    IN A 10.0.0.9