kind: ConfigMap
apiVersion: v1
metadata:
  name: coredns-zones
  namespace: rack01
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/instance: lab-coredns
data:
  db.home.lab: |
    $TTL  30M
    @ IN SOA ns1.home.lab. home.lab. (
        20200101 ; serial
        4H ; refresh
        1H ; retry
        7D ; expire
        4H); Negative Cache TTL
      IN NS ns1
    ns1       IN A 10.0.0.150
    node01    IN A 10.0.0.2
    node02    IN A 10.0.0.3
    node03    IN A 10.0.0.4
    node04    IN A 10.0.0.5
    node05    IN A 10.0.0.6
    node09    IN A 10.0.0.9
    kubernetes IN A 10.0.0.10