kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: slurm
  name: slurm-fs
  namespace: slurm-ns
data:
  # Configuration values can be set as key-value properties
  slurm.conf: |
    # slurm.conf
    SlurmctldHost=node09(192.168.1.198)
    AuthType=auth/munge
    CryptoType=crypto/munge
    MpiDefault=none
    ProctrackType=proctrack/cgroup
    ReturnToService=2
    SlurmctldPidFile=/run/slurmctld.pid
    SlurmctldPort=6817
    SlurmdPidFile=/run/slurmd.pid
    SlurmdPort=6818
    SlurmdSpoolDir=/usr/local/sbin/slurmcd
    SlurmUser=slurm
    StateSaveLocation=/usr/local/sbin/slurmctld
    SwitchType=switch/none
    TaskPlugin=task/affinity
    TaskPluginParam=Sched
    InactiveLimit=0
    KillWait=30
    MinJobAge=300
    SlurmctldTimeout=120
    SlurmdTimeout=300
    Waittime=0
    FastSchedule=1
    SchedulerType=sched/backfill
    SelectType=select/cons_res
    SelectTypeParameters=CR_Core
    AccountingStorageType=accounting_storage/none
    AccountingStoreJobComment=YES
    ClusterName=rpicluster
    JobCompType=jobcomp/none
    JobAcctGatherFrequency=30
    JobAcctGatherType=jobacct_gather/none
    SlurmctldDebug=3
    SlurmctldLogFile=/var/log/supervisor/slurmctld.log
    SlurmdDebug=3
    SlurmdLogFile=/var/log/supervisor/slurmd.log
    # COMPUTE NODES
    # node99 - aka slurm controller living in K8S cluster
    NodeName=node09 NodeAddr=192.168.1.198 CPUs=1 State=UNKNOWN
    # node [02-05] living in RPi cluster
    NodeName=node02 NodeAddr=192.168.1.21 CPUs=4 State=UNKNOWN
    NodeName=node03 NodeAddr=192.168.1.22 CPUs=4 State=UNKNOWN
    NodeName=node04 NodeAddr=192.168.1.23 CPUs=1 State=UNKNOWN
    NodeName=node05 NodeAddr=192.168.1.25 CPUs=4 State=UNKNOWN
    PartitionName=mycluster Nodes=node[02-05] Default=YES MaxTime=INFINITE State=UP
  slurmdbd.conf: |
    #
    # Example slurmdbd.conf file.
    #
    AuthType=auth/munge
    DbdAddr=localhost
    DbdHost=localhost
    SlurmUser=slurm
    DebugLevel=4
    LogFile=/var/log/slurm/slurmdbd.log
    PidFile=/var/run/slurmdbd.pid
    StorageType=accounting_storage/mysql
    StorageHost=localhost
    StoragePass=password
    StorageUser=slurm
    StorageLoc=slurm_acct_db
  gres.conf: |
    Name=gpu Type=titanxp Cores=0

---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: slurm
  name: slurm-config
  namespace: slurm-ns
data:
  # Configuration values can be set as key-value properties
  nfs_server: node01.home.lab
  nfs_mount: /clusterfs
  subPath: clustershare/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm
  namespace: slurm-ns
spec:
  selector:
    matchLabels:
      app: slurm
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: slurm
    spec:
      containers:
      - name: slurm
        #image: titansmc/docker-slurmctld
        image: strusfr/docker-ubuntu1604-slurmctld:latest
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        resources:
          limits:
            cpu: 20m
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 64Mi
        env:
          - name: SLURM_CLUSTER_NAME
            value: rpicluster
          - name: SLURM_CONTROL_MACHINE
            value: node09.home.lab
          - name: SLURM_NODE_NAMES
            value: node[02-05]
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/slurm/slurm.conf
          subPath: slurm.conf
        - name: config-volume
          mountPath: /usr/local/etc/slurm/slurmdbd.conf
          subPath: slurmdbd.conf
        - name: config-volume
          mountPath: /usr/local/etc/slurm/gres.conf
          subPath: gres.conf
        - name: nfs-volume
          mountPath: /clusterfs
      hostname: node09
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
            name: slurm-fs
      - name: nfs-volume
        nfs: 
          # URL for the NFS server
          server: 192.168.1.20 # Change this!
          path: /clusterfs

---
apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  namespace: slurm-ns
spec:
  selector:
    app: slurm
  ports:
    - name: tcp6817
      protocol: TCP
      port: 6817
      targetPort: 6817
    - name: tcp6818
      protocol: TCP
      port: 6818
      targetPort: 6818
    - name: tcp22
      protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
  loadBalancerIP: 192.168.1.198