---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsshare-usb1
spec:
  storageClassName: nfsusb
  capacity:
    storage: 10Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  nfs:
    server: node01.home.lab # Please change this to your NFS server
    path: /mnt/usb2 # Please change this to the relevant share

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsshare-usb2
spec:
  storageClassName: nfsusb
  capacity:
    storage: 10Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  nfs:
    server: node01.home.lab # Please change this to your NFS server
    path: /mnt/usb3 # Please change this to the relevant share

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsshare-usb3
spec:
  storageClassName: nfsusb
  capacity:
    storage: 10Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  nfs:
    server: node01.home.lab # Please change this to your NFS server
    path: /mnt/usb4 # Please change this to the relevant share

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsshare-clusterfs
spec:
  storageClassName: nfsclusterfs
  capacity:
    storage: 30Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  nfs:
    server: node01.home.lab # Please change this to your NFS server
    path: /mnt/usb5 # Please change this to the relevant share