---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-dyn"
spec:
  selector:
    matchLabels:
      app: chartmuseum
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi