---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum-pvc
spec:
  selector:
    matchLabels:
      app: chartmuseum
  accessModes:
    - ReadWriteMany
  storageClassName: nfsusb
  resources:
    requests:
      storage: 10Gi