apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mail
    app: mail
  name: mail
spec:
  selector:
    matchLabels:
      app: mail
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mail
        app: mail
    spec:
      containers:
      - env:
        - name: POSTFIX_myhostname
          value: ska.example.de
        - name: POSTFIX_mynetworks
          value: 0.0.0.0/0
        image: mwader/postfix-relay
        name: mail
        resources: {}
      restartPolicy: Always
status: {}
