apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ska-db
    app: mail
  name: ska-db
spec:
  selector:
    matchLabels:
      app: mail
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ska-db
        app: mail
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: ska-db
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: root-password
        - name: MYSQL_USER
          value: ska-user
        image: mariadb
        name: ska-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: ska-db-claim0
      restartPolicy: Always
      volumes:
      - name: ska-db-claim0
        persistentVolumeClaim:
          claimName: ska-db-claim0
status: {}
