apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ska-php-claim1
  name: ska-php-claim1
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: "nfs-dyn"
status: {}
