client-id: grafana_client
client-secret: dba1f059-8c28-49a8-9804-f47cd2e67b3f
discovery-url: https://keycloak.home.lab/auth/realms/master
skip-upstream-tls-verify: true
skip-openid-provider-tls-verify: true
encryption-key: b8b5931f8385d300e4f3284dcc34345c
listen: 0.0.0.0:4181
secure-cookie: false
enable-logging: true
enable-json-logging: true
enable-default-deny: true
enable-refresh-tokens: true
enable-session-cookies: true
debug: true
ingress.enabled: true
resources:
  - uri: /favicon
    white-listed: true