kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tftp-nfs
  namespace: ftpsvc
  labels:
    app.name: tftpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: tftp-nfs
  volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  name: tftpd
  namespace: ftpsvc
  labels:
    app.name: tftpd
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.199
  ports:
    - port: 69
      targetPort: tftpd
      protocol: UDP
      name: tftpd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftpd
  namespace: ftpsvc
  labels:
    app.name: tftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: tftpd
  template:
    metadata:
      labels:
        app.name: tftpd
    spec:
      containers:
        - name: tftpd
          image: jumanjiman/tftp-hpa:latest
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
            - >
              apt -y install atftpd && atftpd --logfile /dev/stdout --no-fork --verbose 3 --daemon /tftpboot
          ports:
            - name: tftpd
              containerPort: 69
              protocol: UDP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: tftp-nfs
              mountPath: /tftpboot
              subPath: tftp
              readOnly: false
      volumes:
        - name: tftp-nfs
          persistentVolumeClaim:
            claimName: tftp-nfs