---
# Source: forecastle/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: forecastle
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
data:
  config.yaml: |-
    customApps: {}
    headerBackground: null
    headerForeground: null
    instanceName: null
    namespaceSelector:
      any: true
    title: null
    
---
# Source: forecastle/templates/crd.yaml

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: forecastleapps.forecastle.stakater.com
spec:
  group: forecastle.stakater.com
  names:
    kind: ForecastleApp
    listKind: ForecastleAppList
    plural: forecastleapps
    singular: forecastleapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            group:
              type: string
            icon:
              type: string
            instance:
              type: string
            name:
              type: string
            networkRestricted:
              type: boolean
            properties:
              additionalProperties:
                type: string
              type: object
            url:
              type: string
            urlFrom:
              properties:
                ingressRef:
                  type: object
                routeRef:
                  type: object
              type: object
          required:
          - name
          - group
          - icon
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
# Source: forecastle/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
  name: forecastle
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: forecastle
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: forecastle
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: "stakater/forecastle:v1.0.50"
          name: forecastle
          volumeMounts:
          - name: forecastle-config
            mountPath: /etc/forecastle
        - name: gatekeeper
          image: keycloak/keycloak-gatekeeper:7.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
            name: service
          args:
          - --config=/etc/secrets/gatekeeper.yaml
          - --redirection-url=https://apps.home.lab
          - --upstream-url=http://127.0.0.1:80
          - --resources=uri=/*|roles=Admin
          volumeMounts:
            - name: gatekeeper-secrets
              mountPath: /etc/secrets
      volumes:
      - name: forecastle-config
        configMap:
          name: forecastle
      - name: gatekeeper-secrets
        secret:
          secretName: gatekeeper
      serviceAccountName: forecastle

---
# Source: forecastle/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    name: forecastle
    roup: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
  name: forecastle
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "selfsigned-cert"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - apps.home.lab
    secretName: apps-selfsigned-cert-tls
  rules:
  - host: apps.home.lab
    http:
      paths:
      - backend:
          serviceName: forecastle
          servicePort: 3000

---
# Source: forecastle/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
  name: forecastle
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: forecastle-cluster-ingress-role
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
rules:
- apiGroups: ["", "route.openshift.io", "extensions"]
  resources: ["ingresses", "routes", "namespaces"]
  verbs: ["get", "list"]
- apiGroups:
  - forecastle.stakater.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forecastle-cluster-ingress-role-binding
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forecastle-cluster-ingress-role
subjects:
- kind: ServiceAccount
  name: forecastle
  namespace: default

---
# Source: forecastle/templates/route.yaml

---
# Source: forecastle/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
    expose: "false"
  name: forecastle
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: forecastle
    group: com.stakater.platform
    provider: stakater

